---
- name: Installation de l'API Consultation
  hosts: api
  remote_user: root
  vars:
        domain: quchempedia.univ-angers.fr
        repo: https://github.com/sitedevente/QuChemPedIA2020-api.git
        branch: master
        ansible_python_interpreter: /usr/bin/python3
        api_consultation: api_consultation
        api_consultation_folder: Api_Consultation
        user: quchempedia_admin
  roles:
        - utils
        - user
        - nginx
        - flask
