---
- name: Création d'un environnement virtuel python
  shell: python3 -m venv /home/{{ user }}/{{ domain }}/{{ api_consultation_folder }}/quchempedia-venv

- name: Installation des dépendances Python du projet
  pip:
    requirements: /home/{{ user }}/{{ domain }}/requirements.txt
    virtualenv: /home/{{ user }}/{{ domain }}/{{ api_consultation_folder }}/quchempedia-venv

- name: Création du Systemd Unit File
  template: src=templates/{{ api_consultation }}.service.j2 dest=/etc/systemd/system/{{ api_consultation }}.service

- name: Démarrage du processs Systemd
  shell: systemctl start {{ api_consultation }} && systemctl enable {{ api_consultation }}
