---
- name: Creation du user
  when: user is defined
  user: name={{ user }} comment="gitlab admin"

- name: Creation du dossier .ssh
  become: yes
  file:
    path: ~/.ssh
    state: directory

- name: Generation de cle RSA
  openssh_keypair:
    path: "~/.ssh/id_rsa_gitlab"
    type: rsa
    size: 4096
    state: present
    force: no

- name: "{{ user }} devient sudoers"
  when: user is defined
  template:
    src: templates/sudoers.j2
    dest: /etc/sudoers.d/{{ user }}-sudoer
    validate: "visudo -cf %s"
