---
- name: Installation des paquets
  apt:
    name:
      - sudo
      - vim
      - git
      - htop
      - gnupg
    state: latest
    update_cache: yes

- name: Get apt repo key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Installation apt repo
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present
    filename: elastic-7.x.list
    update_cache: yes

- name: Installation de Java
  apt:
    name: default-jdk
    state: present
    update_cache: yes

- name: Install Elasticsearch 7.2.0
  apt:
    name: elasticsearch=7.2.0
    state: present
    update_cache: yes

- name: Chargement de la configuration ElasticSearch
  template: src=elasticsearch.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml

- name: Reload systemd config
  systemd: daemon_reload=yes

- name: Enable service elasticsearch and ensure it is not masked
  systemd:
    name: elasticsearch
    enabled: yes
    masked: no

- name: Ensure ElasticSearch is running
  systemd: state=started name=elasticsearch