# Generated by Django 2.2.16 on 2020-09-17 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formule', models.CharField(default='', max_length=50)),
                ('inchi', models.CharField(default='', max_length=50)),
                ('nb_heavy_atoms', models.CharField(default='', max_length=50)),
                ('charge', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
