# Generated by Django 2.2.16 on 2020-09-28 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoleculeLong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(default='', max_length=50)),
                ('inchi', models.CharField(default='', max_length=50)),
                ('nb_heavy_atoms', models.CharField(default='', max_length=50)),
                ('charge', models.CharField(default='', max_length=50)),
                ('total_molecular_energy', models.CharField(default='', max_length=50)),
                ('basis_set_name', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
