# Generated by Django 2.2.16 on 2020-09-28 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_moleculelong'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moleculelong',
            old_name='basis_set_name',
            new_name='basis_set_md5',
        ),
    ]
